#include "common_ps_fxc.h"

sampler2D SkyTexture            : register(s0);
const float4 Constants0         : register(c0);
#define brightness      Constants0.x
const float4x4 matInvProjViewrot      : register(c11);

static const float PI       = 3.1415926f;
static const float PI2      = PI * 2.0f;
static const float INV_PI   = 1 / PI;
static const float INV_PI2  = 1 / PI2;

struct PS_INPUT {
    float2 P            : VPOS;
    float2 uv           : TEXCOORD0;
};

float4 main( PS_INPUT i ) : COLOR
{
    float2 texCoord = i.uv;

    float4 cameraRay = float4(texCoord * 2.0f - 1.0f, 1.0f, 1.0f);

    float4 viewPos = mul(cameraRay, matInvProjViewrot);
    
    float3 viewDirection = viewPos.xyz /= viewPos.w;

    #if defined(REFLECT_VIEW_RAY)
        viewDirection.z = -viewDirection.z;
    #endif

    viewDirection = normalize(viewDirection);

    float2 uv = float2( atan2( -viewDirection.x, viewDirection.y ) * INV_PI2 + 0.5f, acos( viewDirection.z ) * INV_PI );

    #if defined(MIRROR_SKY)
        uv.y = 1.0 - abs(uv.y * 2.0 - 1.0);
        uv.y = min(0.999, uv.y);
    #endif
    
    float3 sky = tex2D( SkyTexture, uv ).rgb * brightness * LINEAR_LIGHT_SCALE; // HDR_INPUT_MAP_SCALE
    return half4(sky, 1);
}

// https://www.dmitrex.com/publications/Enhancing%20the%20looks%20of%20Source%20Engine%20in%20Military%20Conflict%20Vietnam.pdf

/*
//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float4 Constants0;
//   sampler2D SkyTexture;
//   float4x4 matInvProjViewrot;
//
//
// Registers:
//
//   Name              Reg   Size
//   ----------------- ----- ----
//   Constants0        c0       1
//   matInvProjViewrot c11      4
//   SkyTexture        s0       1
//
    ps_3_0
    def c1, 2, 0, -1, 1
    def c2, 0.0208350997, -0.0851330012, 0.180141002, -0.330299497
    def c3, 0.999866009, -2, 1.57079637, -0.212114394
    def c4, 0.159154952, 0.5, -0.0187292993, 0.0742610022
    def c5, 1.57072878, -2, 3.14159274, 0.318309903
    def c6, -0, 0, -3.14159274, 1
    dcl_texcoord v0.xy
    dcl_2d s0
    mad r0, v0.xyxx, c1.xxyy, c1.zzww
    dp4 r1.x, r0, c14
    rcp r1.x, r1.x
    dp4 r2.x, r0, c11
    dp4 r2.y, r0, c12
    dp4 r2.z, r0, c13
    mul r0.xyz, r1.x, r2
    nrm r1.xyz, r0
    max r0.x, r1_abs.x, r1_abs.y
    rcp r0.x, r0.x
    min r0.y, r1_abs.y, r1_abs.x
    mul r0.x, r0.x, r0.y
    mul r0.y, r0.x, r0.x
    mad r0.z, r0.y, c2.x, c2.y
    mad r0.z, r0.y, r0.z, c2.z
    mad r0.z, r0.y, r0.z, c2.w
    mad r0.y, r0.y, r0.z, c3.x
    mul r0.x, r0.y, r0.x
    mad r0.y, r0.x, c3.y, c3.z
    add r0.z, -r1_abs.x, r1_abs.y
    cmp r0.z, r0.z, c1.y, c1.w
    mad r0.x, r0.y, r0.z, r0.x
    cmp r0.yz, r1, c6.xxyw, c6.xzww
    add r0.x, r0.y, r0.x
    add r0.y, r0.x, r0.x
    max r0.w, -r1.x, r1.y
    cmp r0.w, r0.w, c1.w, c1.y
    min r2.x, r1.y, -r1.x
    cmp r0.w, r2.x, c1.y, r0.w
    mad r0.x, r0.w, -r0.y, r0.x
    mad r0.x, r0.x, c4.x, c4.y
    mad r0.w, r1_abs.z, c4.z, c4.w
    mad r0.w, r0.w, r1_abs.z, c3.w
    mad r0.w, r0.w, r1_abs.z, c5.x
    add r1.x, -r1_abs.z, c1.w
    rsq r1.x, r1.x
    rcp r1.x, r1.x
    mul r0.w, r0.w, r1.x
    mad r1.x, r0.w, c5.y, c5.z
    mad r0.z, r1.x, r0.z, r0.w
    mul r0.y, r0.z, c5.w
    texld r0, r0, s0
    mul r0.xyz, r0, c0.x
    add_pp oC0.xyz, r0, r0
    mov oC0.w, c1.w

// approximately 47 instruction slots used (1 texture, 46 arithmetic)
*/
