r_sky_spherical.name=Spherical Sky
r_sky_spherical.enable=Enable
r_sky_spherical.info=Based on Military Conflict: Vietnam white paper by DmitRex.
r_sky_spherical.brightness=Brightness
r_sky_spherical.adaptation=Enable only if map require
r_sky_spherical.adaptation.help=This is Military Conflict: Vietnam map support. And a new map support with env_sky entity.
r_sky_spherical.notify=For users: If you have a bug with Sky texture, ask map or sky texture addon creator to fix a texture (not a shader creator of this addon).
r_sky_spherical.notify_creator=For addon creators: Use Clamp T, Clamp S flags for a sky texture. And dont use DXT1/DXT5 format. They create a banding. Use RGB888 or RGBA16161616/RGBA16161616F. This addon supports full spherical sky as 4096x2048 (for example). Or a half size of skydome as 4096x1024 as optimization of addon weight.
r_sky_spherical.notify_mapper=For mappers: Use env_sky entity from addon, using env_sky.fgd to add spherical sky to your map.

